version: "2"
run:
  issues-exit-code: 1
linters:
  default: none
  enable:
    - asciicheck
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocognit
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - predeclared
    - reassign
    - revive
    - unparam
    - unused
    - usetesting
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 20
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocognit:
      min-complexity: 10
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
