name: golangci-lint-reusable

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      lint-version:
        required: false
        type: string
        default: v2.0.2
        
jobs:
  golangci:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          check-latest: false
      - uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ inputs.lint-version }}
          args: --timeout=10m
