name: trivy-reusable

on:
  workflow_call:
    inputs:
      scan-type:
        required: false
        type: string
        default: fs
      scan-ref:
        required: false
        type: string
        default: .
      scanners:
        required: false
        type: string
        default: vuln
      exit-code:
        required: false
        type: string
        default: '1'
        
jobs:
  trivy:
    name: Run Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: ${{ inputs.scan-type }}
          scan-ref: ${{ inputs.scan-ref }}
          scanners: ${{ inputs.scanners }}
          format: table
          ignore-unfixed: false
          exit-code: ${{ inputs.exit-code }}
